#!/bin/sh

ln -s /bin/busybox  /bin/[
ln -s /bin/busybox  /bin/[[
ln -s /bin/busybox  /bin/ar
ln -s /bin/busybox  /bin/arch
ln -s /bin/busybox  /bin/ash
ln -s /bin/busybox  /bin/awk
ln -s /bin/busybox  /bin/base64
ln -s /bin/busybox  /bin/basename
ln -s /bin/busybox  /bin/bb
ln -s /bin/busybox  /bin/bbconfig
ln -s /bin/busybox  /bin/bbsh
ln -s /bin/busybox  /bin/bc
ln -s /bin/busybox  /bin/blkdiscard
ln -s /bin/busybox  /bin/bunzip2
ln -s /bin/busybox  /bin/bzcat
ln -s /bin/busybox  /bin/bzip2
ln -s /bin/busybox  /bin/cal
ln -s /bin/busybox  /bin/cat
ln -s /bin/busybox  /bin/chattr
ln -s /bin/busybox  /bin/chgrp
ln -s /bin/busybox  /bin/chmod
ln -s /bin/busybox  /bin/chown
ln -s /bin/busybox  /bin/chpst
ln -s /bin/busybox  /bin/chrt
ln -s /bin/busybox  /bin/chvt
ln -s /bin/busybox  /bin/cksum
ln -s /bin/busybox  /bin/clear
ln -s /bin/busybox  /bin/cmp
ln -s /bin/busybox  /bin/comm
ln -s /bin/busybox  /bin/conspy
ln -s /bin/busybox  /bin/cp
ln -s /bin/busybox  /bin/cpio
ln -s /bin/busybox  /bin/cryptpw
ln -s /bin/busybox  /bin/cttyhack
ln -s /bin/busybox  /bin/cut
ln -s /bin/busybox  /bin/date
ln -s /bin/busybox  /bin/dd
ln -s /bin/busybox  /bin/deallocvt
ln -s /bin/busybox  /bin/df
ln -s /bin/busybox  /bin/diff
ln -s /bin/busybox  /bin/dirname
ln -s /bin/busybox  /bin/dmesg
ln -s /bin/busybox  /bin/dnsdomainname
ln -s /bin/busybox  /bin/dos2unix
ln -s /bin/busybox  /bin/du
ln -s /bin/busybox  /bin/dumpkmap
ln -s /bin/busybox  /bin/dumpleases
ln -s /bin/busybox  /bin/echo
ln -s /bin/busybox  /bin/ed
ln -s /bin/busybox  /bin/egrep
ln -s /bin/busybox  /bin/eject
ln -s /bin/busybox  /bin/env
ln -s /bin/busybox  /bin/envdir
ln -s /bin/busybox  /bin/envuidgid
ln -s /bin/busybox  /bin/expand
ln -s /bin/busybox  /bin/expr
ln -s /bin/busybox  /bin/factor
ln -s /bin/busybox  /bin/fallocate
ln -s /bin/busybox  /bin/false
ln -s /bin/busybox  /bin/fatattr
ln -s /bin/busybox  /bin/fdflush
ln -s /bin/busybox  /bin/fgconsole
ln -s /bin/busybox  /bin/fgrep
ln -s /bin/busybox  /bin/find
ln -s /bin/busybox  /bin/flock
ln -s /bin/busybox  /bin/free
ln -s /bin/busybox  /bin/fsync
ln -s /bin/busybox  /bin/fuser
ln -s /bin/busybox  /bin/getopt
ln -s /bin/busybox  /bin/grep
ln -s /bin/busybox  /bin/groups
ln -s /bin/busybox  /bin/gunzip
ln -s /bin/busybox  /bin/gzip
ln -s /bin/busybox  /bin/hd
ln -s /bin/busybox  /bin/head
ln -s /bin/busybox  /bin/hexdump
ln -s /bin/busybox  /bin/hexedit
ln -s /bin/busybox  /bin/hostname
ln -s /bin/busybox  /bin/id
ln -s /bin/busybox  /bin/install
ln -s /bin/busybox  /bin/ionice
ln -s /bin/busybox  /bin/iostat
ln -s /bin/busybox  /bin/ipcrm
ln -s /bin/busybox  /bin/ipcs
ln -s /bin/busybox  /bin/kbd_mode
ln -s /bin/busybox  /bin/kill
ln -s /bin/busybox  /bin/killall
ln -s /bin/busybox  /bin/last
ln -s /bin/busybox  /bin/less
ln -s /bin/busybox  /bin/link
ln -s /bin/busybox  /bin/linux32
ln -s /bin/busybox  /bin/linux64
ln -s /bin/busybox  /bin/login
ln -s /bin/busybox  /bin/lpq
ln -s /bin/busybox  /bin/lpr
ln -s /bin/busybox  /bin/ls
ln -s /bin/busybox  /bin/lsattr
ln -s /bin/busybox  /bin/lsof
ln -s /bin/busybox  /bin/lspci
ln -s /bin/busybox  /bin/lsscsi
ln -s /bin/busybox  /bin/lsusb
ln -s /bin/busybox  /bin/lzcat
ln -s /bin/busybox  /bin/lzma
ln -s /bin/busybox  /bin/lzop
ln -s /bin/busybox  /bin/lzopcat
ln -s /bin/busybox  /bin/man
ln -s /bin/busybox  /bin/md5sum
ln -s /bin/busybox  /bin/mesg
ln -s /bin/busybox  /bin/microcom
ln -s /bin/busybox  /bin/minips
ln -s /bin/busybox  /bin/mkfifo
ln -s /bin/busybox  /bin/mknod
ln -s /bin/busybox  /bin/mkpasswd
ln -s /bin/busybox  /bin/mktemp
ln -s /bin/busybox  /bin/more
ln -s /bin/busybox  /bin/mount
ln -s /bin/busybox  /bin/mountpoint
ln -s /bin/busybox  /bin/mpstat
ln -s /bin/busybox  /bin/mt
ln -s /bin/busybox  /bin/mv
ln -s /bin/busybox  /bin/nc
ln -s /bin/busybox  /bin/netcat
ln -s /bin/busybox  /bin/netstat
ln -s /bin/busybox  /bin/nice
ln -s /bin/busybox  /bin/nl
ln -s /bin/busybox  /bin/nmeter
ln -s /bin/busybox  /bin/nohup
ln -s /bin/busybox  /bin/nproc
ln -s /bin/busybox  /bin/nsenter
ln -s /bin/busybox  /bin/nslookup
ln -s /bin/busybox  /bin/nuke
ln -s /bin/busybox  /bin/openvt
ln -s /bin/busybox  /bin/passwd
ln -s /bin/busybox  /bin/paste
ln -s /bin/busybox  /bin/patch
ln -s /bin/busybox  /bin/pgrep
ln -s /bin/busybox  /bin/pidof
ln -s /bin/busybox  /bin/ping
ln -s /bin/busybox  /bin/ping6
ln -s /bin/busybox  /bin/pipe_progress
ln -s /bin/busybox  /bin/pkill
ln -s /bin/busybox  /bin/pmap
ln -s /bin/busybox  /bin/printenv
ln -s /bin/busybox  /bin/printf
ln -s /bin/busybox  /bin/ps
ln -s /bin/busybox  /bin/pscan
ln -s /bin/busybox  /bin/pstree
ln -s /bin/busybox  /bin/pwd
ln -s /bin/busybox  /bin/pwdx
ln -s /bin/busybox  /bin/readlink
ln -s /bin/busybox  /bin/realpath
ln -s /bin/busybox  /bin/renice
ln -s /bin/busybox  /bin/reset
ln -s /bin/busybox  /bin/resize
ln -s /bin/busybox  /bin/resume
ln -s /bin/busybox  /bin/rev
ln -s /bin/busybox  /bin/rm
ln -s /bin/busybox  /bin/rx
ln -s /bin/busybox  /bin/script
ln -s /bin/busybox  /bin/scriptreplay
ln -s /bin/busybox  /bin/sed
ln -s /bin/busybox  /bin/seq
ln -s /bin/busybox  /bin/setarch
ln -s /bin/busybox  /bin/setfattr
ln -s /bin/busybox  /bin/setkeycodes
ln -s /bin/busybox  /bin/setpriv
ln -s /bin/busybox  /bin/setserial
ln -s /bin/busybox  /bin/setsid
ln -s /bin/busybox  /bin/setuidgid
ln -s /bin/busybox  /bin/sha1sum
ln -s /bin/busybox  /bin/sha256sum
ln -s /bin/busybox  /bin/sha3sum
ln -s /bin/busybox  /bin/sha512sum
ln -s /bin/busybox  /bin/showkey
ln -s /bin/busybox  /bin/shred
ln -s /bin/busybox  /bin/shuf
ln -s /bin/busybox  /bin/sleep
ln -s /bin/busybox  /bin/softlimit
ln -s /bin/busybox  /bin/sort
ln -s /bin/busybox  /bin/split
ln -s /bin/busybox  /bin/ssl_client
ln -s /bin/busybox  /bin/stat
ln -s /bin/busybox  /bin/strings
ln -s /bin/busybox  /bin/stty
ln -s /bin/busybox  /bin/su
ln -s /bin/busybox  /bin/sum
ln -s /bin/busybox  /bin/svc
ln -s /bin/busybox  /bin/svok
ln -s /bin/busybox  /bin/sync
ln -s /bin/busybox  /bin/tac
ln -s /bin/busybox  /bin/tail
ln -s /bin/busybox  /bin/tar
ln -s /bin/busybox  /bin/tee
ln -s /bin/busybox  /bin/telnet
ln -s /bin/busybox  /bin/test
ln -s /bin/busybox  /bin/tftp
ln -s /bin/busybox  /bin/time
ln -s /bin/busybox  /bin/timeout
ln -s /bin/busybox  /bin/top
ln -s /bin/busybox  /bin/touch
ln -s /bin/busybox  /bin/tr
ln -s /bin/busybox  /bin/traceroute
ln -s /bin/busybox  /bin/traceroute6
ln -s /bin/busybox  /bin/true
ln -s /bin/busybox  /bin/truncate
ln -s /bin/busybox  /bin/ts
ln -s /bin/busybox  /bin/tty
ln -s /bin/busybox  /bin/ttysize
ln -s /bin/busybox  /bin/udhcpc6
ln -s /bin/busybox  /bin/umount
ln -s /bin/busybox  /bin/uname
ln -s /bin/busybox  /bin/uncompress
ln -s /bin/busybox  /bin/unexpand
ln -s /bin/busybox  /bin/uniq
ln -s /bin/busybox  /bin/unit
ln -s /bin/busybox  /bin/unix2dos
ln -s /bin/busybox  /bin/unlink
ln -s /bin/busybox  /bin/unlzma
ln -s /bin/busybox  /bin/unlzop
ln -s /bin/busybox  /bin/unshare
ln -s /bin/busybox  /bin/unxz
ln -s /bin/busybox  /bin/unzip
ln -s /bin/busybox  /bin/uptime
ln -s /bin/busybox  /bin/users
ln -s /bin/busybox  /bin/usleep
ln -s /bin/busybox  /bin/vi
ln -s /bin/busybox  /bin/vlock
ln -s /bin/busybox  /bin/volname
ln -s /bin/busybox  /bin/w
ln -s /bin/busybox  /bin/wall
ln -s /bin/busybox  /bin/watch
ln -s /bin/busybox  /bin/wc
ln -s /bin/busybox  /bin/wget
ln -s /bin/busybox  /bin/which
ln -s /bin/busybox  /bin/who
ln -s /bin/busybox  /bin/whoami
ln -s /bin/busybox  /bin/whois
ln -s /bin/busybox  /bin/xargs
ln -s /bin/busybox  /bin/xxd
ln -s /bin/busybox  /bin/xz
ln -s /bin/busybox  /bin/xzcat
ln -s /bin/busybox  /bin/yes
ln -s /bin/busybox  /bin/zcat

ln -s /bin/busybox  /sbin/acpid
ln -s /bin/busybox  /sbin/addgroup
ln -s /bin/busybox  /sbin/adduser
ln -s /bin/busybox  /sbin/adjtimex
ln -s /bin/busybox  /sbin/arp
ln -s /bin/busybox  /sbin/arping
ln -s /bin/busybox  /sbin/blkid
ln -s /bin/busybox  /sbin/blockdev
ln -s /bin/busybox  /sbin/brctl
ln -s /bin/busybox  /sbin/chat
ln -s /bin/busybox  /sbin/chpasswd
ln -s /bin/busybox  /sbin/chroot
ln -s /bin/busybox  /sbin/crond
ln -s /bin/busybox  /sbin/delgroup
ln -s /bin/busybox  /sbin/deluser
ln -s /bin/busybox  /sbin/depmod
ln -s /bin/busybox  /sbin/devmem
ln -s /bin/busybox  /sbin/dhcprelay
ln -s /bin/busybox  /sbin/ether-wake
ln -s /bin/busybox  /sbin/fbset
ln -s /bin/busybox  /sbin/fdformat
ln -s /bin/busybox  /sbin/fdisk
ln -s /bin/busybox  /sbin/findfs
ln -s /bin/busybox  /sbin/flash_eraseall
ln -s /bin/busybox  /sbin/flash_lock
ln -s /bin/busybox  /sbin/flash_unlock
ln -s /bin/busybox  /sbin/flashcp
ln -s /bin/busybox  /sbin/freeramdisk
ln -s /bin/busybox  /sbin/fsck
ln -s /bin/busybox  /sbin/fsfreeze
ln -s /bin/busybox  /sbin/fstrim
ln -s /bin/busybox  /sbin/ftpd
ln -s /bin/busybox  /sbin/getty
ln -s /bin/busybox  /sbin/ginit
ln -s /bin/busybox  /sbin/halt
ln -s /bin/busybox  /sbin/hdparm
ln -s /bin/busybox  /sbin/httpd
ln -s /bin/busybox  /sbin/hwclock
ln -s /bin/busybox  /sbin/i2cdetect
ln -s /bin/busybox  /sbin/i2cdump
ln -s /bin/busybox  /sbin/i2cget
ln -s /bin/busybox  /sbin/i2cset
ln -s /bin/busybox  /sbin/i2ctransfer
ln -s /bin/busybox  /sbin/ifconfig
ln -s /bin/busybox  /sbin/ifdown
ln -s /bin/busybox  /sbin/ifenslave
ln -s /bin/busybox  /sbin/ifplugd
ln -s /bin/busybox  /sbin/ifup
ln -s /bin/busybox  /sbin/init
ln -s /bin/busybox  /sbin/insmod
ln -s /bin/busybox  /sbin/ip
ln -s /bin/busybox  /sbin/ipaddr
ln -s /bin/busybox  /sbin/iplink
ln -s /bin/busybox  /sbin/ipneigh
ln -s /bin/busybox  /sbin/iproute
ln -s /bin/busybox  /sbin/iprule
ln -s /bin/busybox  /sbin/iptunnel
ln -s /bin/busybox  /sbin/killall5
ln -s /bin/busybox  /sbin/loadfont
ln -s /bin/busybox  /sbin/loadkmap
ln -s /bin/busybox  /sbin/logread
ln -s /bin/busybox  /sbin/losetup
ln -s /bin/busybox  /sbin/lsmod
ln -s /bin/busybox  /sbin/makedevs
ln -s /bin/busybox  /sbin/mdev
ln -s /bin/busybox  /sbin/mim
ln -s /bin/busybox  /sbin/mkdosfs
ln -s /bin/busybox  /sbin/mke2fs
ln -s /bin/busybox  /sbin/mkfs.ext2
ln -s /bin/busybox  /sbin/mkfs.reiser
ln -s /bin/busybox  /sbin/mkfs.vfat
ln -s /bin/busybox  /sbin/mkswap
ln -s /bin/busybox  /sbin/modinfo
ln -s /bin/busybox  /sbin/modprobe
ln -s /bin/busybox  /sbin/nameif
ln -s /bin/busybox  /sbin/nanddump
ln -s /bin/busybox  /sbin/nandwrite
ln -s /bin/busybox  /sbin/nbd-client
ln -s /bin/busybox  /sbin/nologin
ln -s /bin/busybox  /sbin/ntpd
ln -s /bin/busybox  /sbin/partprobe
ln -s /bin/busybox  /sbin/pivot_root
ln -s /bin/busybox  /sbin/popmaildir
ln -s /bin/busybox  /sbin/poweroff
ln -s /bin/busybox  /sbin/powertop
ln -s /bin/busybox  /sbin/raidautorun
ln -s /bin/busybox  /sbin/rdate
ln -s /bin/busybox  /sbin/readahead
ln -s /bin/busybox  /sbin/reboot
ln -s /bin/busybox  /sbin/rmmod
ln -s /bin/busybox  /sbin/route
ln -s /bin/busybox  /sbin/rtcwake
ln -s /bin/busybox  /sbin/run-init
ln -s /bin/busybox  /sbin/runlevel
ln -s /bin/busybox  /sbin/sendmail
ln -s /bin/busybox  /sbin/setconsole
ln -s /bin/busybox  /sbin/setfont
ln -s /bin/busybox  /sbin/setlogcons
ln -s /bin/busybox  /sbin/start-stop-daemon
ln -s /bin/busybox  /sbin/swapoff
ln -s /bin/busybox  /sbin/swapon
ln -s /bin/busybox  /sbin/switch_root
ln -s /bin/busybox  /sbin/sysctl
ln -s /bin/busybox  /sbin/tc
ln -s /bin/busybox  /sbin/telnetd
ln -s /bin/busybox  /sbin/tftpd
ln -s /bin/busybox  /sbin/tunctl
ln -s /bin/busybox  /sbin/tune2fs
ln -s /bin/busybox  /sbin/ubiattach
ln -s /bin/busybox  /sbin/ubidetach
ln -s /bin/busybox  /sbin/ubimkvol
ln -s /bin/busybox  /sbin/ubirename
ln -s /bin/busybox  /sbin/ubirmvol
ln -s /bin/busybox  /sbin/ubirsvol
ln -s /bin/busybox  /sbin/ubiupdatevol
ln -s /bin/busybox  /sbin/udhcpc
ln -s /bin/busybox  /sbin/udhcpd
ln -s /bin/busybox  /sbin/uevent
ln -s /bin/busybox  /sbin/vconfig
ln -s /bin/busybox  /sbin/watchdog
ln -s /bin/busybox  /sbin/zcip

