#!/bin/sh

microgentoo_base() {

	CONTAINER=$(buildah from scratch)

	export CHOST=$(chroot $CHROOTDIR emerge -- --info |grep CHOST|sed 's/CHOST="//g'|sed 's/"//g')
	export GCC_MAJOR=$(chroot $CHROOTDIR gcc --version|sed 's/gcc (Gentoo //g'|line 0|sed 's/\..*//g'|sed 's/^.* //g')

	_print_header "base" "latest"

	buildah copy $CONTAINER $ROOTDIR/bin/mkdir /bin/
	buildah copy $CONTAINER $ROOTDIR/bin/chmod /bin/
	buildah copy $CONTAINER $ROOTDIR/bin/ls /bin/
	buildah copy $CONTAINER $ROOTDIR/bin/ln /bin/
	buildah copy $CONTAINER $ROOTDIR/bin/rm /bin/
	buildah copy $CONTAINER $ROOTDIR/bin/sh /bin/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/iconv /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/bin/chown /bin/
	buildah copy $CONTAINER $ROOTDIR/usr/sbin/useradd /usr/sbin/
	buildah copy $CONTAINER $ROOTDIR/usr/sbin/groupadd /usr/sbin/

	# etc
	buildah copy $CONTAINER passwd /etc/
	buildah copy $CONTAINER group /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/ld.so.conf /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/ssl/ /etc/ssl/
	buildah copy $CONTAINER $ROOTDIR/etc/env.d/ /etc/env.d/
	buildah copy $CONTAINER $ROOTDIR/etc/environment.d/ /etc/environment.d/
	buildah copy $CONTAINER $ROOTDIR/etc/ca-certificates.conf /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/services /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/protocols /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/os-release /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/DIR_COLORS /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/profile /etc/
	buildah copy $CONTAINER $ROOTDIR/etc/profile.env /etc/

	if [ "${CHOST}" == "x86_64-gentoo-linux-musl" ]; then
		export CHOSTBASE="musl"
		buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libc.so /usr/${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/ld-musl-x86_64.so.1 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/etc/ld-musl-x86_64.path /etc/
	else
		export CHOSTBASE="gnu"
		buildah copy $CONTAINER $ROOTDIR/etc/nsswitch.conf /etc/
		buildah copy $CONTAINER $ROOTDIR/etc/ld.so.cache /etc/
		buildah copy $CONTAINER $ROOTDIR/etc/ld.so.conf.d/ /etc/ld.so.conf.d/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libc.so.6 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/ld-linux-x86-64.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libm.so.6 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libdl.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libutil.so.1 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libnss_compat.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libnss_db.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libnss_dns.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libnss_files.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libresolv.so.2 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libpthread.so.0 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/librt.so.1 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libcrypt.so.1 /${BASELIB}/
		buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libcrypt.so.2 /${BASELIB}/
	fi

	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libacl.so.1 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libattr.so.1 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libtinfo.so.6 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libtinfow.so.6 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libz.so.1 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libbz2.so.1 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libreadline.so.8 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libtinfo.so.6 /${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/${BASELIB}/libtinfow.so.6 /${BASELIB}/

	# usr
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libcrypto.so.3 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libbsd.so.0 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libmd.so.0 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libssl.so.3 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libffi.so.8 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libexpat.so.1 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_MAJOR}/libgomp.so.1.0.0 /usr/lib/gcc/${CHOST}/${GCC_MAJOR}/
	buildah copy $CONTAINER $ROOTDIR/usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_MAJOR}/libgcc_s.so.1 /usr/lib/gcc/${CHOST}/${GCC_MAJOR}/
	buildah copy $CONTAINER $ROOTDIR/usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_MAJOR}/libstdc++.so.6 /usr/lib/gcc/${CHOST}/${GCC_MAJOR}/

	buildah run $CONTAINER -- /bin/ln -s /usr/${BASELIB}/libcrypto.so.3 /usr/${BASELIB}/libcrypto.so
	buildah run $CONTAINER -- /bin/ln -s /usr/${BASELIB}/libssl.so.3 /usr/${BASELIB}/libssl.so

	buildah run $CONTAINER -- /bin/ln -s /usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_MAJOR}/libgomp.so.1.0.0 /usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_MAJOR}/libgomp.so.1
	# other
	buildah copy $CONTAINER $ROOTDIR/usr/share/ca-certificates/ /usr/share/ca-certificates/
	buildah run $CONTAINER -- mkdir /{root,var,tmp,var/empty,var/log,var/tmp,sbin,/usr/bin}
	buildah run $CONTAINER -- chmod 777 /tmp

	buildah commit $CONTAINER $PREFIX/base:latest
	buildah rm $CONTAINER
}

