#!/bin/sh

############# busybox ##################
microgentoo_busybox() {

	_print_header "busybox"

	CONTAINER=$(buildah from microgentoo/$CHOSTBASE/base)

	export BUSYBOX_VERSION_LABEL=$(chroot $CHROOTDIR equery -- list "*busybox*"|line 2 |awk -F '/' '{print $2}'|sed 's/busybox-//g'|awk -F "." '{print $1"."$2".y"}')

	buildah copy $CONTAINER $ROOTDIR/bin/busybox /bin/
	buildah copy $CONTAINER busybox.sh /

	_copy_ldd $CONTAINER /bin/busybox

	buildah run $CONTAINER -- /bin/busybox sh /busybox.sh
	buildah run $CONTAINER -- rm /busybox.sh

	#_cleanup_utils $CONTAINER

	# commit
	buildah commit $CONTAINER microgentoo/$CHOSTBASE/busybox:${BUSYBOX_VERSION_LABEL}
	buildah rm $CONTAINER
}


