#!/bin/sh

############# busybox ##################
microgentoo_busybox() {

	CONTAINER=$(buildah from $PREFIX/base)

	export BUSYBOX_VERSION_LABEL=$(chroot $CHROOTDIR equery -- list "*busybox*"|line 2 |awk -F '/' '{print $2}'|sed 's/busybox-//g'|awk -F "." '{print $1"."$2".y"}')

	_print_header "busybox" $BUSYBOX_VERSION_LABEL

	buildah copy $CONTAINER $ROOTDIR/bin/busybox /bin/
	buildah copy $CONTAINER busybox.sh /

	_copy_ldd $CONTAINER /bin/busybox

	buildah run $CONTAINER -- rm /bin/chmod
	buildah run $CONTAINER -- rm /bin/mkdir
	buildah run $CONTAINER -- rm /bin/ls
	buildah run $CONTAINER -- rm /bin/sh
	buildah run $CONTAINER -- rm /bin/chown
	buildah run $CONTAINER -- rm /usr/sbin/useradd
	buildah run $CONTAINER -- rm /usr/sbin/groupadd
	buildah run $CONTAINER -- rm /bin/rm
	
	buildah run $CONTAINER -- /bin/busybox sh /busybox.sh
	buildah run $CONTAINER -- mv /bin/ln /bin/tmpln
	buildah run $CONTAINER -- /bin/tmpln -s /bin/busybox /bin/ln
	buildah run $CONTAINER -- rm /bin/tmpln

	buildah run $CONTAINER -- rm /busybox.sh

	# commit
	buildah commit $CONTAINER $PREFIX/busybox:${BUSYBOX_VERSION_LABEL}
	buildah rm $CONTAINER
}


