#!/bin/sh

############# openjdk ###############
microgentoo_openjdk() {

	CONTAINER=$(buildah from $PREFIX/base)

	export JAVACMD=$(chroot $CHROOTDIR find -- /usr/lib/ -executable -iname "java")

	export OPENJDK_SLOT_VERSION=$(chroot $CHROOTDIR $JAVACMD -version 2>&1 | line 1|awk '{print $3}'|sed 's/"//g' | awk -F "." '{print $1}')
	export OPENJDK_VERSION_LABEL=$(chroot $CHROOTDIR $JAVACMD -version 2>&1 | line 1|awk '{print $3}'|sed 's/"//g' | awk -F "." '{print $1"."$2".y"}')

	_print_header "openjdk" $OPENJDK_VERSION_LABEL

	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/ /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/

	for jbin in `chroot $CHROOTDIR ls /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/bin`
	do
		buildah run $CONTAINER -- ln -s /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/bin/${jbin} /usr/bin/${jbin}
	done

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER $PREFIX/openjdk:${OPENJDK_VERSION_LABEL}
	buildah rm $CONTAINER
}

