#!/bin/sh

############# openssh client ########
microgentoo_openssh_client() {

	_print_header "openssh client"

	CONTAINER=$(buildah from microgentoo/base)

	export SSH_VERSION=$(chroot $CHROOTDIR equery -- list "*openssh*"|line 2 |awk -F '/' '{print $2}'|sed 's/openssh-//g'|sed 's/_.*.$//g'| awk -F "." '{print $1"."$2.".y"}')

	_copy_ldd $CONTAINER /usr/sbin/sshd

	buildah copy $CONTAINER $ROOTDIR/etc/ssh/moduli /etc/ssh/
	buildah copy $CONTAINER $ROOTDIR/etc/ssh/ssh_config /etc/ssh/

	buildah copy $CONTAINER $ROOTDIR/usr/bin/ssh /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/scp /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/sftp /usr/bin/

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER microgentoo/openssh-client:${SSH_VERSION}
	buildah rm $CONTAINER
}


