#!/bin/sh

############# openjdk ###############
microgentoo_openjdk() {
	CONTAINER=$(buildah from microgentoo/$CHOSTBASE/base)

	export OPENJDK_SLOT_VERSION=$(chroot $CHROOTDIR equery -- list "*openjdk*"|line 2 |awk -F '/' '{print $2}'|sed 's/openjdk-//g'|awk -F "." '{print $1}')
	export OPENJDK_VERSION_LABEL=$(chroot $CHROOTDIR equery -- list "*openjdk*"|line 2 |awk -F '/' '{print $2}'|sed 's/openjdk-//g'|awk -F "." '{print $1"."$2".y"}')

	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/ /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/

	for jbin in `ls /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/bin`
	do
		buildah run $CONTAINER -- ln -s /usr/${BASELIB}/openjdk-${OPENJDK_SLOT_VERSION}/bin/${jbin} /usr/bin/${jbin}
	done

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER microgentoo/$CHOSTBASE/openjdk:${OPENJDK_VERSION_LABEL}
	buildah rm $CONTAINER
}


