#!/bin/sh

############# packer ################
microgentoo_packer() {

	_print_header "packer"

	CONTAINER=$(buildah from microgentoo/base)

	export PACKER_VERSION_LABEL=$(chroot $CHROOTDIR packer version|sed 's/Packer v//g' | line 1|awk -F "." '{print $1"."$2.".y"}')

	buildah copy $CONTAINER $ROOTDIR/usr/bin/packer /usr/bin/

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER microgentoo/packer:${PACKER_VERSION_LABEL}
	buildah rm $CONTAINER
}
