#!/bin/sh

############# packer ################
gentoo_container_packer() {
	CONTAINER=$(buildah from gentoo-container-base)

	export PACKER_VERSION_LABEL=$(packer version|sed 's/Packer v//g' | line 1|awk -F "." '{print $1"."$2.".y"}')

	buildah copy $CONTAINER $ROOTDIR/usr/bin/packer /usr/bin/

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER gentoo-container-packer:${PACKER_VERSION_LABEL}
	buildah rm $CONTAINER
}
