#!/bin/sh

############# php fpm ##################
microgentoo_php_fpm() {

	export PHP_VERSION=$(chroot $CHROOTDIR php-fpm -v |awk '/^PHP/ {print $2}'|awk -F "." '{print $1"."$2}')
	export PHP_VERSION_LABEL=$(chroot $CHROOTDIR php-fpm -v |awk '/^PHP/ {print $2}'|awk -F "." '{print $1"."$2.".y"}')

	_print_header "php fpm $PHP_VERSION_LABEL"

	CONTAINER=$(buildah from microgentoo/$CHOSTBASE/base)

	buildah copy $CONTAINER $ROOTDIR/etc/php/fpm-php${PHP_VERSION}/ /etc/php/fpm-php${PHP_VERSION}/
	buildah run $CONTAINER -- sh -c "/bin/ln -s /etc/php/fpm-php${PHP_VERSION} /etc/php/fpm-php"

	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/php${PHP_VERSION}/bin/php-fpm /usr/${BASELIB}/php${PHP_VERSION}/bin/ 
	#buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/php${PHP_VERSION}/bin/phar.phar /usr/${BASELIB}/php${PHP_VERSION}/bin/ 
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/php${PHP_VERSION}/bin/php-config /usr/${BASELIB}/php${PHP_VERSION}/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/php${PHP_VERSION}/bin/phpize /usr/${BASELIB}/php${PHP_VERSION}/bin/

	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/php${PHP_VERSION}/${BASELIB}/* /usr/${BASELIB}/php${PHP_VERSION}/${BASELIB}/

	#buildah run $CONTAINER -- ln -s /usr/${BASELIB}/php${PHP_VERSION}/bin/phar.phar /usr/${BASELIB}/php${PHP_VERSION}/bin/phar

	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../${BASELIB}/php${PHP_VERSION}/bin/php-fpm php-fpm"
	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../${BASELIB}/php${PHP_VERSION}/bin/php-config php-config"
	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../${BASELIB}/php${PHP_VERSION}/bin/phpize phpize"
	#buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../${BASELIB}/php${PHP_VERSION}/bin/phar.phar phar"

	_copy_ldd $CONTAINER /usr/bin/php-fpm

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER microgentoo/$CHOSTBASE/php-fpm:${PHP_VERSION_LABEL}
	buildah rm $CONTAINER
}

