#!/bin/sh 

############# python ################
microgentoo_python() {

	CONTAINER=$(buildah from $PREFIX/base)

	export PYTHON_VERSION=$(chroot $CHROOTDIR python -V|awk '{print $2}'|awk -F"." '{print $1"."$2}')
	export PYTHON_VERSION_LABEL=$(chroot $CHROOTDIR python -V|awk '{print $2}'|awk -F"." '{print $1"."$2.".y"}')

	_print_header "python" $PYTHON_VERSION_LABEL

	buildah copy --ignorefile .containerignore --contextdir $ROOTDIR/usr/ $CONTAINER $ROOTDIR/usr/lib/python${PYTHON_VERSION}/ /usr/lib/python${PYTHON_VERSION}/
	buildah copy $CONTAINER $ROOTDIR/usr/lib/python-exec/python${PYTHON_VERSION}/* /usr/lib/python-exec/python${PYTHON_VERSION}/
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libpython${PYTHON_VERSION}.so.1.0 /usr/${BASELIB}/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/python${PYTHON_VERSION} /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/python-exec2c /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/bin/python${PYTHON_VERSION}-config /usr/bin/
	buildah copy $CONTAINER $ROOTDIR/usr/lib/python-exec/python-exec2 /usr/lib/python-exec/
	buildah copy $CONTAINER $ROOTDIR/etc/python-exec/ /etc/python-exec/

	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libffi.so.8 /usr/${BASELIB}/

	buildah run $CONTAINER -- sh -c 'cd /usr/bin && ln -s python-exec2c python'
	buildah run $CONTAINER -- sh -c 'cd /usr/bin && ln -s python-exec2c python3'
	buildah run $CONTAINER -- sh -c 'cd /usr/bin && ln -s ../lib/python-exec/python-exec2 pip'
	buildah run $CONTAINER -- sh -c 'cd /usr/bin && ln -s ../lib/python-exec/python-exec2 pip3'
	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../lib/python-exec/python-exec2 pip${PYTHON_VERSION}"
	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../lib/python-exec/python-exec2 pyenv"
	buildah run $CONTAINER -- sh -c "cd /usr/bin && ln -s ../lib/python-exec/python-exec2 python3-config"

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER $PREFIX/python:${PYTHON_VERSION_LABEL}
	buildah rm $CONTAINER
}

