#!/bin/sh

############# zeromq ############
microgentoo_zeromq() {

	CONTAINER=$(buildah from $PREFIX/base)

	export ZEROMQ_PKGPF=$(chroot $CHROOTDIR find /var/db/pkg/ -iwholename '*net-libs/zeromq*'|line 1)
	export ZEROMQ_VERSION_LABEL=$(chroot $CHROOTDIR cat $ZEROMQ_PKGPF"/"PF |sed 's/zeromq-//g' |awk -F "." '{print $1"."$2.".y"}')

	_print_header "zeromq" $ZEROMQ_VERSION_LABEL
	
	buildah copy $CONTAINER $ROOTDIR/usr/${BASELIB}/libzmq.so.5 /usr/${BASELIB}/

	_copy_ldd $CONTAINER /usr/${BASELIB}/libzmq.so.5

	# clean and commit
	_cleanup_utils $CONTAINER
	buildah commit $CONTAINER $PREFIX/zeromq:${ZEROMQ_VERSION_LABEL}
	buildah rm $CONTAINER
}


